// Localhost routes

// Courses collection
// Get courses
GET http://localhost:8080/courses
###

// Get single course
GET http://localhost:8080/courses/63475b5e0fb5a41682d4c457
###

// Create new course
POST http://localhost:8080/courses/
content-type: application/json

{
    "courseName": "Something",
    "courseDuration": "5 hours"
}
###

// Update course
PUT http://localhost:8080/courses/63475b5e0fb5a41682d4c457
content-type: application/json

{
	"courseName": "Anything",
}
###

// Delete course
DELETE http://localhost:8080/courses/63475b5e0fb5a41682d4c457
###

// Details collection
// Get course details
GET http://localhost:8080/courseDetails
###

// Get single course
GET http://localhost:8080/courseDetails/6348c54dd44ae7e8fe03e47c
###

// Create details
POST http://localhost:8080/courseDetails
Content-Type: application/json

{
    "courseName": "a",
    "courseDuration": "",
    "courseDescrition": "",
    "coursePrice": "",
    "courseInstructor": "",
    "courseRating": "",
    "courseTopics": [],
    "courseRelatedArticles": [],
}
###

// Update details
PUT http://localhost:8080/courseDetails/6348c54dd44ae7e8fe03e47c
Content-Type: application/json

{
    "courseName": "HAHA",
}
###

// Delete details
DELETE http://localhost:8080/courseDetails/6348c54dd44ae7e8fe03e47c
###

// Instructors collection
// Get instructors
GET http://localhost:8080/courseInstructors
###

// Get single instructor
GET http://localhost:8080/courseInstructors/6348c55ed44ae7e8fe03e482
###

// Add instructor
POST http://localhost:8080/courseInstructors
Content-Type: application/json

{
    "courseName": "",
    "instructorFirstName": "",
    "instructorLastName": "",
    "instructorEmail": "",
    "instructorPhone": "",
}
###

// Add instructor
PUT http://localhost:8080/courseInstructors/6348c55ed44ae7e8fe03e482
Content-Type: application/json

{
    "courseName": "",
    "instructorFirstName": "",
}
###

// Delete instructor
DELETE http://localhost:8080/courseInstructors/6348c55ed44ae7e8fe03e482
###

// Get Authorization
GET http://localhost:8080/authorization/login
###

// Render routes

// Course collection
// Get courses
GET https://ammonquarshie-onlinecourseapi.onrender.com/courses
###

// Get single course
GET https://ammonquarshie-onlinecourseapi.onrender.com/courses/63475b5e0fb5a41682d4c457
###

// Create new course
POST https://ammonquarshie-onlinecourseapi.onrender.com/courses
content-type: application/json

{
    "courseName": "Something",
    "courseDuration": "5 hours"
}
###

// Update course
PUT https://ammonquarshie-onlinecourseapi.onrender.com/courses/63475b5e0fb5a41682d4c457
content-type: application/json

{
	"courseName": "Anything",
}
###

// Delete course
DELETE https://ammonquarshie-onlinecourseapi.onrender.com/courses/63475b5e0fb5a41682d4c457
###

// Details collection
// Get course details
GET https://ammonquarshie-onlinecourseapi.onrender.com/courseDetails
###

// Get single course
GET https://ammonquarshie-onlinecourseapi.onrender.com/6348c54dd44ae7e8fe03e47c
###

// Create details
POST https://ammonquarshie-onlinecourseapi.onrender.com
Content-Type: application/json

{
    "courseName": "a",
    "courseDuration": "",
    "courseDescrition": "",
    "coursePrice": "",
    "courseInstructor": "",
    "courseRating": "",
    "courseTopics": [],
    "courseRelatedArticles": [],
}
###

// Update details
PUT https://ammonquarshie-onlinecourseapi.onrender.com/6348c54dd44ae7e8fe03e47c
Content-Type: application/json

{
    "courseName": "HAHA",
}
###

// Delete details
DELETE https://ammonquarshie-onlinecourseapi.onrender.com/6348c54dd44ae7e8fe03e47c
###

// Instructors collection
// Get instructors
GET https://ammonquarshie-onlinecourseapi.onrender.com/courseInstructors
###

// Get single instructor
GET https://ammonquarshie-onlinecourseapi.onrender.com/courseInstructors/6348c55ed44ae7e8fe03e482
###

// Add instructor
POST https://ammonquarshie-onlinecourseapi.onrender.com/courseInstructors
Content-Type: application/json

{
    "courseName": "",
    "instructorFirstName": "",
    "instructorLastName": "",
    "instructorEmail": "",
    "instructorPhone": "",
}
###

// Add instructor
PUT https://ammonquarshie-onlinecourseapi.onrender.com/courseInstructors/6348c55ed44ae7e8fe03e482
Content-Type: application/json

{
    "courseName": "",
    "instructorFirstName": "",
}
###

// Delete instructor
DELETE https://ammonquarshie-onlinecourseapi.onrender.com/courseInstructors/6348c55ed44ae7e8fe03e482
###

// Get Authorization
GET http://ammonquarshie-onlinecourseapi.onrender.com/authorization/login
###